nlfunc: specify calling convention for NL functions
MSVC in release mode errors on func_call with obscure error C2099,
which is about floating point ... Let's see if specifying the calling
convention helps